#!/usr/bin/env bash

here="$(cd $(dirname $0) && pwd)"

(cd $here &&
   exec docker build \
	--build-arg http_proxy=$http_proxy \
	--build-arg https_proxy=$https_proxy \
	--build-arg ftp_proxy=$ftp_proxy \
	--build-arg no_proxy=$no_proxy \
	--tag ecmwf/dask-distributed-test \
	--file Dockerfile \
	.)
